#!/usd/bin/env python3
import mysql.connector
from __future__ import print_function

# Defining database configs
config_accounts = {
        'user': 'azimuth3_alex',
        'password': 'Songo2016',
        'host': '50.87.248.164',
        'database': 'azimuth3_accounts'}

config_payments = {
        'user': 'azimuth3_alex',
        'password': 'Songo2016',
        'host': '50.87.248.164',
        'database': 'azimuth3_payments'}

DB_NAME = azimuth3_payments

# Establishing a connection with error handling
try:
    cnx = mysql.connector.connect(**config)
    cursor = cnx.cursor()
    

except mysql.connector.Error as err:
    if err.errno == errorcode.ER_ACCESS_DENIED_ERROR:
        print("Something is wrong with your user name or password")
    elif err.errno == errorcode.ER_BAD_DB_ERROR:
        print("Database does not exist")
    else:
        print(err)

else:
    cnx.close()
